server:
  port: 9000

spring:
  ai:
    model:
      chat: openai
    openai:
      chat:
        model: gpt-3.5-turbo
        api-key: ${OPENAI_API_KEY}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
